
package com.hc.henghuirong.server.octopus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OctopusService", targetNamespace = "http://ws.credithc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OctopusService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mqGetRequest", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqGetRequest")
    @ResponseWrapper(localName = "mqGetRequestResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqGetRequestResponse")
    public void mqGetRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendOperateLog", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.SendOperateLog")
    @ResponseWrapper(localName = "sendOperateLogResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.SendOperateLogResponse")
    public void sendOperateLog(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mqGetResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqGetResponse")
    @ResponseWrapper(localName = "mqGetResponseResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqGetResponseResponse")
    public void mqGetResponse(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.hc.henghuirong.server.octopus.MqResponseVo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mqSendRtRequest", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendRtRequest")
    @ResponseWrapper(localName = "mqSendRtRequestResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendRtRequestResponse")
    public MqResponseVo mqSendRtRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mqSendResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendResponse")
    @ResponseWrapper(localName = "mqSendResponseResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendResponseResponse")
    public void mqSendResponse(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mgGetRtRequest", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MgGetRtRequest")
    @ResponseWrapper(localName = "mgGetRtRequestResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MgGetRtRequestResponse")
    public void mgGetRtRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mqSendRequest", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendRequest")
    @ResponseWrapper(localName = "mqSendRequestResponse", targetNamespace = "http://ws.credithc.com/", className = "com.hc.henghuirong.server.octopus.MqSendRequestResponse")
    public void mqSendRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        MqRequestVo arg0);

}
