
package com.hc.henghuirong.server.octopus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OctopusServiceService", targetNamespace = "http://ws.credithc.com/", wsdlLocation = "http://10.100.13.122:8083/octopus/webservice/esbWS?wsdl")
public class OctopusServiceService
    extends Service
{

    private final static URL OCTOPUSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException OCTOPUSSERVICESERVICE_EXCEPTION;
    private final static QName OCTOPUSSERVICESERVICE_QNAME = new QName("http://ws.credithc.com/", "OctopusServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.13.122:8083/octopus/webservice/esbWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OCTOPUSSERVICESERVICE_WSDL_LOCATION = url;
        OCTOPUSSERVICESERVICE_EXCEPTION = e;
    }

    public OctopusServiceService() {
        super(__getWsdlLocation(), OCTOPUSSERVICESERVICE_QNAME);
    }

    public OctopusServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OCTOPUSSERVICESERVICE_QNAME, features);
    }

    public OctopusServiceService(URL wsdlLocation) {
        super(wsdlLocation, OCTOPUSSERVICESERVICE_QNAME);
    }

    public OctopusServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OCTOPUSSERVICESERVICE_QNAME, features);
    }

    public OctopusServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OctopusServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OctopusService
     */
    @WebEndpoint(name = "OctopusServicePort")
    public OctopusService getOctopusServicePort() {
        return super.getPort(new QName("http://ws.credithc.com/", "OctopusServicePort"), OctopusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OctopusService
     */
    @WebEndpoint(name = "OctopusServicePort")
    public OctopusService getOctopusServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.credithc.com/", "OctopusServicePort"), OctopusService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OCTOPUSSERVICESERVICE_EXCEPTION!= null) {
            throw OCTOPUSSERVICESERVICE_EXCEPTION;
        }
        return OCTOPUSSERVICESERVICE_WSDL_LOCATION;
    }

}
